// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class WingResources
{
        public const string achievement_wing_expert = "CgkIpKWz-qwMEAIQDQ"; // <GPGSID>
        public const string achievement_first_fifty = "CgkIpKWz-qwMEAIQEQ"; // <GPGSID>
        public const string achievement_little_experienced = "CgkIpKWz-qwMEAIQEA"; // <GPGSID>
        public const string achievement_sign_in = "CgkIpKWz-qwMEAIQAA"; // <GPGSID>
        public const string achievement_wing_master = "CgkIpKWz-qwMEAIQBw"; // <GPGSID>
        public const string achievement_pro_flyer = "CgkIpKWz-qwMEAIQAQ"; // <GPGSID>
        public const string achievement_sophomore = "CgkIpKWz-qwMEAIQEg"; // <GPGSID>
        public const string achievement_half_century = "CgkIpKWz-qwMEAIQBQ"; // <GPGSID>
        public const string achievement_professor = "CgkIpKWz-qwMEAIQFw"; // <GPGSID>
        public const string achievement_twofifty = "CgkIpKWz-qwMEAIQFQ"; // <GPGSID>
        public const string achievement_silver_medalist = "CgkIpKWz-qwMEAIQCQ"; // <GPGSID>
        public const string achievement_fivehundreds = "CgkIpKWz-qwMEAIQFA"; // <GPGSID>
        public const string achievement_dark_knight = "CgkIpKWz-qwMEAIQDg"; // <GPGSID>
        public const string leaderboard_games_played = "CgkIpKWz-qwMEAIQDw"; // <GPGSID>
        public const string achievement_200__50 = "CgkIpKWz-qwMEAIQDA"; // <GPGSID>
        public const string achievement_100__50 = "CgkIpKWz-qwMEAIQCw"; // <GPGSID>
        public const string achievement_onetwothree = "CgkIpKWz-qwMEAIQEw"; // <GPGSID>
        public const string achievement_century = "CgkIpKWz-qwMEAIQBg"; // <GPGSID>
        public const string achievement_gold_medalist = "CgkIpKWz-qwMEAIQCA"; // <GPGSID>
        public const string achievement_entry_to_the_world = "CgkIpKWz-qwMEAIQAw"; // <GPGSID>
        public const string achievement_addicted = "CgkIpKWz-qwMEAIQFg"; // <GPGSID>
        public const string achievement_bronze_medalist = "CgkIpKWz-qwMEAIQCg"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIpKWz-qwMEAIQAg"; // <GPGSID>

}

